networks:
  water-dispenser-network:
    name: water-dispenser-network

services:
  water-dispenser:
    image: 192.168.1.254:5000/water-dispenser:1.0.0
    container_name: water-dispenser
    privileged: true
    volumes:
      - /etc/armbian-release:/etc/armbian-release
    ports:
      - "80:80"
    networks:
      - water-dispenser-network
    restart: unless-stopped
